# Generated by Django 2.0.2 on 2018-03-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20180306_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='link',
            field=models.URLField(max_length=1000),
        ),
    ]
