# Generated by Django 2.0.2 on 2018-03-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20180306_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='note',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
