# Generated by Django 2.0.2 on 2018-03-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_problem_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='note',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
