# Generated by Django 2.0.2 on 2018-03-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solve_activities', '0002_auto_20180307_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='solve',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
