# Generated by Django 2.0.2 on 2018-03-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='oj',
            new_name='online_judge',
        ),
        migrations.AlterField(
            model_name='problem',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=100, unique=True),
        ),
    ]
