# Generated by Django 2.0.2 on 2018-03-05 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20180305_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='online_judge',
            new_name='oj_name',
        ),
    ]
