# Generated by Django 2.0.2 on 2018-03-05 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, max_length=20, unique=True)),
                ('semester', models.TextField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('problem_count', models.PositiveIntegerField(default=4)),
                ('cut_off', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SheetMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='sheets.Sheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sheet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sheet',
            name='members',
            field=models.ManyToManyField(through='sheets.SheetMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sheetmember',
            unique_together={('sheet', 'user')},
        ),
    ]
