# Generated by Django 2.0.2 on 2018-03-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20180305_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='semester',
            field=models.CharField(max_length=10),
        ),
    ]
