# Generated by Django 2.0.2 on 2018-03-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_auto_20180305_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetmember',
            name='solve_count',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
