# Generated by Django 2.0.2 on 2018-03-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_auto_20180318_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='year',
        ),
        migrations.AddField(
            model_name='sheet',
            name='batch',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
