# Generated by Django 2.0.2 on 2018-03-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_auto_20180319_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='batch',
            field=models.CharField(max_length=20),
        ),
    ]
