# Generated by Django 2.0.3 on 2018-03-27 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_auto_20180328_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='sheets',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheets.Sheet'),
        ),
    ]
