# Generated by Django 2.0.2 on 2018-03-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
