# Generated by Django 2.0.2 on 2018-03-26 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheets', '0007_auto_20180319_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='problem_count',
            new_name='problems_added',
        ),
        migrations.RenameField(
            model_name='sheetmember',
            old_name='user',
            new_name='member',
        ),
        migrations.AlterUniqueTogether(
            name='sheetmember',
            unique_together={('sheet', 'member')},
        ),
    ]
