# Generated by Django 2.1.3 on 2019-06-05 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badges', '0002_auto_20190605_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeacheiver',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badges.Badge'),
        ),
        migrations.AlterUniqueTogether(
            name='badgeacheiver',
            unique_together={('user', 'badge', 'date')},
        ),
    ]
