# Generated by Django 2.1.3 on 2019-06-10 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_auto_20190605_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
